# Generated by Django 5.1.5 on 2025-01-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CIIC", models.CharField(max_length=11)),
                ("Nome", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Cadastrodeficha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ficha", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="NomeResponsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=30)),
                ("sobrenome", models.CharField(max_length=30)),
            ],
        ),
    ]
